CREATE TABLE IF NOT EXISTS socios(
id_socio INTEGER PRIMARY KEY,
nombre TEXT NOT NULL,
email TEXT UNIQUE NOT NULL,
fecha_ingreso DATE DEFAULT CURRENT_DATE);
CREATE TABLE IF NOT EXISTS eventos(
id_evento INTEGER PRIMARY KEY,
nombre TEXT NOT NULL,
capacidad INTEGER CHECK(capacidad>0));
